name: tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    paths:
      - "shap/**"
      - "tests/**"
      - "data/**"
      - ".github/workflows/run_tests.yml"
      - "pyproject.toml"
      - "setup.py"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  # Cancel only PR intermediate builds
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  run_tests:
    strategy:
      matrix:
        include:
          # Test on windows/mac, just one job each
          - os: windows-latest
            python-version: "3.11"
            extras: "test"
      fail-fast: true
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install libomp (macOS)
        if: matrix.os == 'macos-latest'
        run: brew install libomp
      - name: Install dependencies
        # Do regular install NOT editable install: see GH #3020
        run: |
          python -m pip install --upgrade uv
          # uv pip install --system '.[${{ matrix.extras }},plots]'
          #
          uv pip install --system matplotlib<3.9.1
          # python -m pip install --upgrade pip matplotlib==3.9.1  # works..
      - name: Test with pytest
        # Ensure we avoid adding current working directory to sys.path:
        # - Use "pytest" over "python -m pytest"
        # - Use "append" import mode rather than default "prepend"
        run: >
          pytest --durations=20
          --cov --cov-report=xml
          --mpl-generate-summary=html --mpl-results-path=./mpl-results
          --import-mode=append
      - name: Upload mpl test report
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: mpl-results-${{ matrix.python-version }}-${{ runner.os }}-${{ matrix.extras }}
          path: mpl-results/
          if-no-files-found: ignore
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
